### PR TITLE
Fix test devices

### PR DESCRIPTION
**Pull request by QuLogic**
Tests were not correctly falling back to the test device when real devices were not available.

BTW, why not run these tests on Travis-CI?

### CODE REVIEW

**Comment by jflesch** [comment]
Thanks :)

Regarding Travis-CI, I was actually thinking of [installing a Builbot](https://github.com/openpaperwork/paperwork/issues/708) (I already have a dedicated server building nightly and distributing the Flatpak version of Paperwork). It would be not only for Pyinsane, but also Pyocr, Libpilllowfight, and Paperwork.
Quite frankly, I haven't had time yet to look at which solution would be best nor to set one of them up, and I don't know when I will.

[If you have time for that and are willing, you can also contribute on that point :-)](https://github.com/openpaperwork/paperwork/wiki/Contributing#sysadmin)

**Comment by QuLogic** [comment]
Ah, I forgot about the port to GNOME infrastructure; surely they will have some sort of builtin CI with GitLab.

**Comment by jflesch** [comment]
I guess. But right now they are not ready anyway, and I don't know how long they will need to get their Gitlab out of testing.

**Comment by QuLogic** [comment]
Looks like it might be possible to migrate now: https://wiki.gnome.org/GitLab/IncubatorReqs

**Comment by jflesch** [comment]
Good to know. I'm still planning on switching to gitlab.gnome.org. But while waiting for Gnome's Gitlab, I made my [own buildbot](https://origami.openpaper.work). So at least the CI issue is solved (and also it updates the Flatpak repository automatically and rebuilds Windows versions automatically as well).

**Pull request merged**
